name: Build and GH-Page Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          
      - name: Install Jupyter
        run: pip install jupyter


      - name: Install Bundler
        run: gem install bundler

      - name: Install Gem Dependencies
        run: bundle install

      - name: Install Node Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _site